name: Prod AWS Deployment - Specific Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - global
          - prod
      Apply:
        description: 'Apply Terraform changes'
        required: true
        default: false
        type: boolean

permissions:
  id-token: write 
  contents: read 

defaults:
  run:
    working-directory: aws/prod-infra

jobs:
  plan:
    name: Plan - ${{ inputs.environment }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::696793786584:role/GHA-CodeBuild-Service-Role
          aws-region: eu-west-2
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4
        
      - name: Install Checkov
        run: pip3 install checkov==3.2.365
        
      - name: Initialize Terraform
        run: ./run.sh ${{ inputs.environment }} init
        
      - name: Run Terraform validation and checkov
        run: make check ${{ inputs.environment }}
        
      - name: Run Terraform plan
        id: plan
        run: make plan ${{ inputs.environment }}
  
  apply:
    name: Apply - ${{ inputs.environment }}
    needs: plan
    if: ${{ github.event.inputs.Apply == 'true' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment == 'global' && 'Global' || inputs.environment == 'prod' && 'Prod' }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::696793786584:role/GHA-CodeBuild-Service-Role
          aws-region: eu-west-2
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4
          
      - name: Initialize Terraform
        run: ./run.sh ${{ inputs.environment }} init
        
      - name: Run Terraform plan
        run: make plan ${{ inputs.environment }}

      - name: Run Terraform apply
        run: make apply ${{ inputs.environment }}